### ISSUE TITLE
Readme example compilation error

### ISSUE THREAD

**Issue by obasille** [NordicSemiconductor/Android-BLE-Library#376]
Readme example doesn't compile with 2.4.0 because BleManager constructor now requires an argument.
Also I think the "Log.println" line is missing the tag argument.

Thank you for this great library!
